#!/bin/sh

full_config=()
conf_files=($(find $HOME/.ssh/conf.d -name *.conf | tr '\n' ' '))

for conf_file in "${conf_files[@]}"; do
  # echo "Loading configuration file: ${conf_file}"

  config="$(cat ${conf_file})"

  replaced_config="${config//IdentityFile /IdentityFile $(dirname $conf_file)/}"
  title="# Config file: ${conf_file} #"
  separator=$(eval "printf '#%.0s' {1..${#title}}")

  replaced_config=$(printf "\r$separator\n$title\n$separator\n\n${replaced_config}\n\n\r")

  full_config+=("$replaced_config")
done

backup_timestamp=$(date +"%Y-%m-%d_%H-%M-%S")
# Backup the current config file
cp $HOME/.ssh/config $HOME/.ssh/config_$backup_timestamp.bak

# Create the $HOME/.ssh/config file
echo "${full_config[@]}" > $HOME/.ssh/config

# Remove the backup if it is equal
diff $HOME/.ssh/config $HOME/.ssh/config_$backup_timestamp.bak > /dev/null && rm -f $HOME/.ssh/config_$backup_timestamp.bak